# Generated by Django 6.0.2 on 2026-03-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_alter_sosrequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='type',
            field=models.CharField(choices=[('Ambulance', 'Ambulance'), ('Police', 'Police'), ('Fire Emergency', 'Fire Emergency'), ('Medical Help', 'Medical Help'), ('NGO Support', 'NGO Support')], max_length=50),
        ),
    ]
